networks:
  tour-net:
    driver: bridge

volumes:
  tour-postgres-data:

services:
  tour-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tour-api
    networks: [tour-net]
    ports:
      - "8080:8080"
    environment:
      DB_HOST: tour-postgres
      DB_PORT: 5432
      DB_NAME: tour
      DB_USER: tour_user
      DB_PASSWORD: tour_password
      SPRING_PROFILES_ACTIVE: dev