FROM maven:3.9.14-eclipse-temurin-25 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -q

COPY src ./src

RUN mvn package --no-transfer-progress -DskipTests

FROM openjdk:25-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

COPY /src/main/resources/application.yml /app/config/application.yml

LABEL org.opencontainers.image.title="Spring Boot Application API"
LABEL org.opencontainers.image.description="Spring Boot Application API"

ENV SPRING_CONFIG_LOCATION=/app/config/application.yml

RUN mkdir /tmp/tomcat static && chown -R 2320:2320 /app

USER 2320:2320
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost:8080 || exit 1