/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/producers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List producers */
        get: operations["listProducers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/infrastructures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List infrastructures */
        get: operations["listInfrastructures"];
        put?: never;
        /** Create an infrastructure */
        post: operations["createInfrastructure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/infrastructures/{infrastructureId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                infrastructureId: components["parameters"]["InfrastructureId"];
            };
            cookie?: never;
        };
        /** Get an infrastructure */
        get: operations["getInfrastructure"];
        /** Update an infrastructure */
        put: operations["updateInfrastructure"];
        post?: never;
        /** Delete an infrastructure */
        delete: operations["deleteInfrastructure"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vehicles */
        get: operations["listVehicles"];
        put?: never;
        /** Create a vehicle */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        /** Get a vehicle */
        get: operations["getVehicle"];
        /** Update a vehicle */
        put: operations["updateVehicle"];
        post?: never;
        /** Soft-delete a vehicle */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: operations["listCustomers"];
        put?: never;
        /** Create a customer */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        /** Get a customer */
        get: operations["getCustomer"];
        /** Update a customer */
        put: operations["updateCustomer"];
        post?: never;
        /** Soft-delete a customer */
        delete: operations["deleteCustomer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List routes */
        get: operations["listRoutes"];
        put?: never;
        /** Create a route */
        post: operations["createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        /** Get a route (with stops) */
        get: operations["getRoute"];
        /** Update a route */
        put: operations["updateRoute"];
        post?: never;
        /** Soft-delete a route */
        delete: operations["deleteRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate a route (with its stops) */
        post: operations["duplicateRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a route (locks it) */
        post: operations["validateRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder stops to minimise distance (TSP) */
        post: operations["optimizeRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a stop to a route */
        post: operations["createStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/stops/{stopId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
                stopId: components["parameters"]["StopId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a stop */
        put: operations["updateStop"];
        post?: never;
        /** Remove a stop (sequences are renumbered) */
        delete: operations["deleteStop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/stops/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Re-order all stops of a route */
        patch: operations["reorderStops"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["listProducts"];
        put?: never;
        /** Create a product */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        /** Get a product */
        get: operations["getProduct"];
        /** Update a product */
        put: operations["updateProduct"];
        post?: never;
        /** Soft-delete a product */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stopId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: components["parameters"]["StopId"];
            };
            cookie?: never;
        };
        /** List items delivered at a stop */
        get: operations["listStopItems"];
        put?: never;
        /** Add a product line to a stop */
        post: operations["createStopItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stopId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: components["parameters"]["StopId"];
                itemId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a stop item */
        put: operations["updateStopItem"];
        post?: never;
        /** Remove a stop item */
        delete: operations["deleteStopItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search an address (proxy to geocoding provider) */
        post: operations["geocode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute distance and duration between ordered waypoints */
        post: operations["computeRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        /** KPI snapshot for a single route */
        get: operations["getRouteStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated KPIs across routes over a period */
        get: operations["getGlobalStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/email": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send the route summary by email */
        post: operations["emailRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/export.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        /** Export a route as a PDF document */
        get: operations["exportRoutePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{routeId}/export.gpx": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        /** Export a route as a GPX track */
        get: operations["exportRouteGpx"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/optimization/daily-routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize direct-vs-hub assignment for a producer's daily deliveries
         * @description Solves a MILP that assigns each planned delivery stop (for the given
         *     producer and date) either to a direct delivery by the producer, or to
         *     transit through one of the coop-available hubs for xDock last-mile.
         *     Minimizes the total daily cost including producer fleet cost, hub
         *     fleet cost, handling fees and the detour cost of visiting a hub.
         */
        post: operations["optimizeDailyRouting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Producer: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            contact?: string | null;
            address?: string | null;
            province?: string | null;
            /** @default false */
            isBio: boolean;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        ProducerPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Producer"][];
        };
        Error: {
            /** @example VALIDATION_FAILED */
            code: string;
            /** @example Field 'name' must not be blank */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Page: {
            /** @example 42 */
            total: number;
            /** @example 50 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        /** @enum {string} */
        VehicleType: "van" | "light_truck" | "heavy_truck";
        /** @enum {string} */
        FuelType: "diesel" | "gasoline" | "cng" | "electric" | "hybrid";
        /** @enum {string} */
        DriverType: "employee" | "owner" | "external";
        /** @enum {string} */
        CustomerType: "restaurant" | "school" | "csa" | "shop" | "individual" | "pickup_point" | "other";
        /** @enum {string} */
        DayOfWeek: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
        /** @enum {string} */
        RouteStatus: "draft" | "validated" | "completed" | "cancelled";
        /** @enum {string} */
        StopOperation: "delivery" | "pickup" | "relay_point";
        /** @enum {string} */
        ProductCategory: "dry" | "fresh" | "frozen";
        Infrastructure: {
            /** Format: uuid */
            readonly id: string;
            drySurfaceM2: number;
            freshSurfaceM2: number;
            frozenSurfaceM2: number;
            prepSurfaceM2: number;
            /** Format: double */
            depotLatitude?: number | null;
            /** Format: double */
            depotLongitude?: number | null;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        InfrastructureCreate: {
            /** @default 0 */
            drySurfaceM2: number;
            /** @default 0 */
            freshSurfaceM2: number;
            /** @default 0 */
            frozenSurfaceM2: number;
            /** @default 0 */
            prepSurfaceM2: number;
            /** Format: double */
            depotLatitude?: number | null;
            /** Format: double */
            depotLongitude?: number | null;
        };
        InfrastructureUpdate: {
            drySurfaceM2?: number;
            freshSurfaceM2?: number;
            frozenSurfaceM2?: number;
            prepSurfaceM2?: number;
            /** Format: double */
            depotLatitude?: number | null;
            /** Format: double */
            depotLongitude?: number | null;
        };
        InfrastructurePage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Infrastructure"][];
        };
        Vehicle: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly producerId?: string;
            type: components["schemas"]["VehicleType"];
            fuel: components["schemas"]["FuelType"];
            /** Format: double */
            consumptionL100Km?: number | null;
            /** Format: double */
            fuelPrice?: number | null;
            /** Format: double */
            amortizationEurKm?: number | null;
            refrigerated: boolean;
            driverType?: components["schemas"]["DriverType"];
            /** Format: double */
            hourlyCost?: number | null;
            prepTimeMin?: number;
            loadingTimeMin?: number;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        VehicleCreate: {
            /** Format: uuid */
            producerId: string;
            type: components["schemas"]["VehicleType"];
            fuel: components["schemas"]["FuelType"];
            /** Format: double */
            consumptionL100Km?: number;
            /** Format: double */
            fuelPrice?: number;
            /** Format: double */
            amortizationEurKm?: number;
            /** @default false */
            refrigerated: boolean;
            driverType?: components["schemas"]["DriverType"];
            /** Format: double */
            hourlyCost?: number;
            /** @default 0 */
            prepTimeMin: number;
            /** @default 0 */
            loadingTimeMin: number;
        };
        VehicleUpdate: {
            type?: components["schemas"]["VehicleType"];
            fuel?: components["schemas"]["FuelType"];
            /** Format: double */
            consumptionL100Km?: number;
            /** Format: double */
            fuelPrice?: number;
            /** Format: double */
            amortizationEurKm?: number;
            refrigerated?: boolean;
            driverType?: components["schemas"]["DriverType"];
            /** Format: double */
            hourlyCost?: number;
            prepTimeMin?: number;
            loadingTimeMin?: number;
        };
        VehiclePage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Vehicle"][];
        };
        Customer: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly producerId?: string;
            name: string;
            type?: components["schemas"]["CustomerType"];
            address?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            /** Format: email */
            contactEmail?: string | null;
            contactPhone?: string | null;
            deliveryHours?: string | null;
            notes?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        CustomerCreate: {
            /** Format: uuid */
            producerId: string;
            name: string;
            type?: components["schemas"]["CustomerType"];
            address?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: email */
            contactEmail?: string;
            contactPhone?: string;
            deliveryHours?: string;
            notes?: string;
        };
        CustomerUpdate: {
            name?: string;
            type?: components["schemas"]["CustomerType"];
            address?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /** Format: email */
            contactEmail?: string;
            contactPhone?: string;
            deliveryHours?: string;
            notes?: string;
        };
        CustomerPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Customer"][];
        };
        Route: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly producerId?: string;
            /** Format: uuid */
            vehicleId?: string | null;
            name: string;
            dayOfWeek?: components["schemas"]["DayOfWeek"];
            /** Format: date */
            scheduledDate?: string | null;
            status: components["schemas"]["RouteStatus"];
            /** Format: double */
            distanceKm?: number | null;
            durationMin?: number | null;
            /** Format: double */
            totalCost?: number | null;
            /** Format: double */
            totalRevenue?: number | null;
            /** Format: double */
            profitabilityRatio?: number | null;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        RouteDetail: components["schemas"]["Route"] & {
            stops?: components["schemas"]["Stop"][];
        };
        RouteCreate: {
            /** Format: uuid */
            producerId: string;
            name: string;
            /** Format: uuid */
            vehicleId?: string;
            dayOfWeek?: components["schemas"]["DayOfWeek"];
            /** Format: date */
            scheduledDate?: string;
        };
        RouteUpdate: {
            name?: string;
            /** Format: uuid */
            vehicleId?: string;
            dayOfWeek?: components["schemas"]["DayOfWeek"];
            /** Format: date */
            scheduledDate?: string;
        };
        RoutePage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Route"][];
        };
        Stop: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly routeId?: string;
            /** Format: uuid */
            customerId?: string | null;
            sequence: number;
            operation: components["schemas"]["StopOperation"];
            /** Format: double */
            amountEur?: number;
            durationMin?: number;
            /** Format: double */
            distanceFromPrevKm?: number | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            address?: string | null;
        };
        StopCreate: {
            /** Format: uuid */
            customerId?: string;
            operation: components["schemas"]["StopOperation"];
            /**
             * Format: double
             * @default 0
             */
            amountEur: number;
            /** @default 15 */
            durationMin: number;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            address?: string;
        };
        StopUpdate: components["schemas"]["StopCreate"];
        StopReorderRequest: {
            /** @description Stop IDs in the desired order */
            order: string[];
        };
        Product: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            category?: string | null;
            ean?: string | null;
            unit: string;
            storageType?: string | null;
            /** @default false */
            isBio: boolean;
            certification?: string | null;
            /** Format: uuid */
            readonly producerId: string;
        };
        ProductCreate: {
            /** Format: uuid */
            producerId: string;
            name: string;
            category?: string | null;
            ean?: string | null;
            unit: string;
            storageType?: string | null;
            /** @default false */
            isBio: boolean;
            certification?: string | null;
        };
        ProductUpdate: {
            name?: string;
            category?: string | null;
            ean?: string | null;
            unit?: string;
            storageType?: string | null;
            /** @default false */
            isBio: boolean;
            certification?: string | null;
        };
        ProductPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Product"][];
        };
        StopItem: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly stopId: string;
            /** Format: uuid */
            productId: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            unitPrice?: number | null;
        };
        StopItemCreate: {
            /** Format: uuid */
            productId: string;
            /** Format: double */
            quantity: number;
            /** Format: double */
            unitPrice?: number;
        };
        StopItemUpdate: components["schemas"]["StopItemCreate"];
        GeocodeResult: {
            displayName: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** Format: double */
            confidence?: number | null;
        };
        Waypoint: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        RoutingRequest: {
            waypoints: components["schemas"]["Waypoint"][];
            /** @default false */
            returnGeometry: boolean;
        };
        RoutingLeg: {
            /** Format: double */
            distanceKm?: number;
            durationMin?: number;
        };
        RoutingResult: {
            /** Format: double */
            distanceKm?: number;
            durationMin?: number;
            legs?: components["schemas"]["RoutingLeg"][];
            /** @description Encoded polyline (optional) */
            geometry?: string;
        };
        RouteStats: {
            /** Format: uuid */
            routeId?: string;
            /** Format: double */
            distanceKm?: number;
            durationMin?: number;
            /** Format: double */
            totalCost?: number;
            /** Format: double */
            totalRevenue?: number;
            /** Format: double */
            profitabilityRatio?: number;
            /** Format: double */
            costPerStop?: number;
            /** Format: double */
            revenuePerKm?: number;
        };
        GlobalStats: {
            routesCount?: number;
            /** Format: double */
            totalDistanceKm?: number;
            totalDurationMin?: number;
            /** Format: double */
            totalCost?: number;
            /** Format: double */
            totalRevenue?: number;
            /** Format: double */
            averageRatio?: number;
        };
        OptimizationInput: {
            /**
             * Format: date
             * @description Scheduled date of the routes to consider (all producers)
             */
            date: string;
            /**
             * Format: double
             * @description Coop handling fee charged per unit of volume transiting through a hub
             * @default 0
             */
            handlingFeePerUnit: number;
            /**
             * Format: double
             * @description Flat fee applied each time a hub is used in the day
             * @default 0
             */
            openingFee: number;
            /**
             * Format: int64
             * @description Solver time budget in milliseconds
             * @default 10000
             */
            maxSolveTimeMs: number;
            /**
             * Format: double
             * @description Vitesse moyenne (km/h) utilisée pour estimer le temps de trajet (coût chauffeur)
             * @default 50
             */
            avgSpeedKmPerHour: number;
        };
        OptimizationResult: {
            /** Format: date */
            date: string;
            /** @description OPTIMAL | FEASIBLE | NO_STOPS | NO_PRODUCER_WITH_DEPOT | NO_HUBS_AVAILABLE */
            solverStatus: string;
            /** Format: int64 */
            solveTimeMs?: number;
            stopCount: number;
            producerCount: number;
            hubsAvailable?: number;
            hubsUsed?: number;
            /**
             * Format: double
             * @description Total cost if every producer delivered every stop direct from its own depot
             */
            baselineAllDirectCostEur: number;
            /** Format: double */
            optimizedCostEur: number;
            /**
             * Format: double
             * @description baseline - optimized
             */
            savingsEur: number;
            assignments: components["schemas"]["OptimizationStopAssignment"][];
            /** @description Bulk drops each producer must perform at each used hub */
            transfers: components["schemas"]["OptimizationProducerHubTransfer"][];
            /** @description Per-hub last-mile manifest (all producers combined) */
            pickingLists: components["schemas"]["OptimizationHubPickingList"][];
            /** @description Reconstructed tours (loops) for mapping/visualization */
            tours?: components["schemas"]["OptimizationTour"][];
        };
        /** @enum {string} */
        OptimizationTourType: "DIRECT" | "BULK_TRANSFER" | "LAST_MILE";
        OptimizationTour: {
            tourId: string;
            type: components["schemas"]["OptimizationTourType"];
            /** Format: uuid */
            producerId?: string | null;
            /** Format: uuid */
            hubId?: string | null;
            start: components["schemas"]["Waypoint"];
            end: components["schemas"]["Waypoint"];
            orderedStopIds: string[];
            legs: components["schemas"]["OptimizationTourLeg"][];
            /** Format: double */
            totalKm: number;
            /** Format: double */
            totalTravelCostEur: number;
        };
        OptimizationTourLeg: {
            /** Format: uuid */
            fromStopId?: string | null;
            /** Format: uuid */
            toStopId?: string | null;
            from: components["schemas"]["Waypoint"];
            to: components["schemas"]["Waypoint"];
            /** Format: double */
            km: number;
            /** Format: double */
            travelCostEur: number;
        };
        OptimizationStopAssignment: {
            /** Format: uuid */
            stopId: string;
            /** Format: uuid */
            routeId: string;
            /** Format: uuid */
            producerId: string;
            sequence: number;
            /** @enum {string} */
            mode: "DIRECT" | "VIA_HUB";
            /**
             * Format: uuid
             * @description Infrastructure ID of the chosen hub; null if mode=DIRECT
             */
            hubId?: string | null;
            /** Format: double */
            volume: number;
            /** Format: double */
            directCostEur: number;
            /**
             * Format: double
             * @description Cost of the chosen hub last-mile; null if mode=DIRECT
             */
            viaHubCostEur?: number | null;
            /**
             * Format: double
             * @description Geocoded stop location (for mapping purposes); null if not geocoded
             */
            latitude?: number | null;
            /**
             * Format: double
             * @description Geocoded stop location (for mapping purposes); null if not geocoded
             */
            longitude?: number | null;
        };
        OptimizationProducerHubTransfer: {
            /** Format: uuid */
            producerId: string;
            /** Format: uuid */
            hubId: string;
            /**
             * Format: double
             * @description Round-trip detour depot → hub → depot
             */
            detourKm: number;
            /** Format: double */
            detourCostEur: number;
            /** Format: double */
            totalVolume: number;
            stopIds: string[];
        };
        OptimizationHubPickingList: {
            /** Format: uuid */
            hubId: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            stopIds: string[];
            contributingProducers: string[];
            /** Format: double */
            totalVolume: number;
            /** Format: double */
            openingCostEur: number;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict with current resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request rejected due to business rule violation */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        /** @description Producer scope for the request */
        ProducerIdQuery: string;
        ProducerId: string;
        VehicleId: string;
        CustomerId: string;
        RouteId: string;
        StopId: string;
        ProductId: string;
        InfrastructureId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of producers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProducerPage"];
                };
            };
        };
    };
    listInfrastructures: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of infrastructures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructurePage"];
                };
            };
        };
    };
    createInfrastructure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfrastructureCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Infrastructure"];
                };
            };
        };
    };
    getInfrastructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                infrastructureId: components["parameters"]["InfrastructureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infrastructure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Infrastructure"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateInfrastructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                infrastructureId: components["parameters"]["InfrastructureId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfrastructureUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Infrastructure"];
                };
            };
        };
    };
    deleteInfrastructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                infrastructureId: components["parameters"]["InfrastructureId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listVehicles: {
        parameters: {
            query: {
                /** @description Producer scope for the request */
                producerId: components["parameters"]["ProducerIdQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of vehicles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiclePage"];
                };
            };
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    getVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleUpdate"];
            };
        };
        responses: {
            /** @description Updated vehicle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    listCustomers: {
        parameters: {
            query: {
                /** @description Producer scope for the request */
                producerId: components["parameters"]["ProducerIdQuery"];
                /** @description Case-insensitive name or address match */
                search?: string;
                type?: components["schemas"]["CustomerType"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    deleteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    listRoutes: {
        parameters: {
            query: {
                /** @description Producer scope for the request */
                producerId: components["parameters"]["ProducerIdQuery"];
                dayOfWeek?: components["schemas"]["DayOfWeek"];
                status?: components["schemas"]["RouteStatus"];
                scheduledDate?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of routes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePage"];
                };
            };
        };
    };
    createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route with its stops */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route already validated / immutable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    duplicateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New route */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
        };
    };
    validateRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validated route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route is not in a validatable state (no stops, etc.) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    optimizeRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Optimized route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteDetail"];
                };
            };
        };
    };
    createStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopCreate"];
            };
        };
        responses: {
            /** @description Created stop */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"];
                };
            };
        };
    };
    updateStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
                stopId: components["parameters"]["StopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"];
                };
            };
        };
    };
    deleteStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
                stopId: components["parameters"]["StopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reorderStops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopReorderRequest"];
            };
        };
        responses: {
            /** @description Stops after reordering */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stop"][];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query: {
                /** @description Producer scope for the request */
                producerId: components["parameters"]["ProducerIdQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listStopItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: components["parameters"]["StopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopItem"][];
                };
            };
        };
    };
    createStopItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: components["parameters"]["StopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopItemCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopItem"];
                };
            };
        };
    };
    updateStopItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: components["parameters"]["StopId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopItemUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopItem"];
                };
            };
        };
    };
    deleteStopItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: components["parameters"]["StopId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    geocode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 12 rue du marché, Marche-en-Famenne */
                    query: string;
                };
            };
        };
        responses: {
            /** @description Candidate places */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"][];
                };
            };
        };
    };
    computeRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingRequest"];
            };
        };
        responses: {
            /** @description Routing result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingResult"];
                };
            };
        };
    };
    getRouteStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteStats"];
                };
            };
        };
    };
    getGlobalStats: {
        parameters: {
            query: {
                /** @description Producer scope for the request */
                producerId: components["parameters"]["ProducerIdQuery"];
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated KPIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStats"];
                };
            };
        };
    };
    emailRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    to: string[];
                    subject?: string;
                    message?: string;
                };
            };
        };
        responses: {
            /** @description Accepted for delivery */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportRoutePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    exportRouteGpx: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPX file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/gpx+xml": string;
                };
            };
        };
    };
    optimizeDailyRouting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizationInput"];
            };
        };
        responses: {
            /** @description Optimization result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationResult"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
